### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by ristokitsing** [ristokitsing/EMS#17]
Add a 'Sign up / Log in' page to HTML prototype.

**Comment by loo242** [comment]
Please, revise the page as per we've discussed
Sign up / Log in

email
password
Log in
Sign up

**Comment by vanessascode** [comment]
I uploaded what I had last week, @kRVRKV please improve the login

**Comment by kRVRKV** [comment]
done. only slight padding issues

**Comment by vanessascode** [comment]
we do not need "sign in" button and "sign in/sign up" button, lets keep only "sign in/sign up"
